Typeslint/github-AutoResponse

src/index.ts
**Describe the bug**
Change contributor label instead of getting `codeowners approved`
**To Reproduce**
Steps to reproduce the behavior:
1. Fork the repository and make a change
2. Create a pull request as a member it needs to be reviewed by a member, contributor, or collaborator.
3. Approve code review
**Expected behavior**
API set `Others Approve` label to PRs
=> fix: change others approved label

src/index.ts
check PRs type is "User" or "Bot", give a different statement for each value
```ts
switch (payload) {
case value:
break;
default:
break;
}
```
=> feat: check PRs type

src/index.ts
**Please describe the changes this PR makes and why it should be merged:**
get sha from object and avoid Explicit Any for ESLint
```ts
if ("sha" in res.data)
```
**Reference:**
https://github.com/Muunatic/github-AutoResponse/blob/a88ca5e49353b4a1d1eefa17bc6d288c64b33c15/src/index.ts#L80
https://github.com/Muunatic/github-AutoResponse/blob/a88ca5e49353b4a1d1eefa17bc6d288c64b33c15/src/index.ts#L81
=> refactor: get sha from object

src/index.ts
this pull request introduces a significant enhancement that empowers `member` to grant approval for pull requests (PRs) to be automatically merged by non-members. with this feature in place, the development workflow becomes more efficient and seamless, as authorized contributors can trigger the merging process without direct member intervention
=> feat: allow member to merge pull requests

src/index.ts
In this commit, the label "closed" has been updated to "Closed" to adherence to proper labeling conventions within the automation system.
=> chore: Adjust label for proper case sensitivity

src/index.ts
feature has been added to the codebase that enables the [API](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request) to check the mergeability of pull requests. ensures that a pull request is mergeable and prevent potential merge conflicts
=> feat: implement pull request mergeability check

src/index.ts
fix `no-misused-promises` issues due to a missing await
=> refactor: avoid no-misused-promises

src/structures/listener.ts
This pull request aims to enhance the error handling in the Node.js application by explicitly specifying the `error` parameter as an instance of the `Error` interface in the event listener.
=> refactor: Add error interface

src/index.ts
This pull request aims to enhance the reply context functionality in our GitHub automaton to improve the clarity and relevance of automated responses. Currently, the automaton's replies lack context, which can lead to confusion and inefficiencies in codebase
=> chore: Adjust reply context

src/index.ts
This pull request addresses the need to enable automaton replies outside the core directory. Currently, automaton replies are limited to within the core directory. This should fix any reply issues when a pull request is outside the core directory.
=> fix: Add reply outside core dir

src/index.ts
This pull request addresses the issue #34 by Replacing the usage of the 'fetch' function in our codebase with the `fetch` function provided by the Node.js 18 module. 
Removed the `fetch` function calls from the codebase.
Utilized the `fetch` function from the Node.js 18 module instead.
=> feat(API)!: Replace fetch with Node.js 18 module

.github/workflows/build.yml
add build CI and update node version to v18
=> build(CI): add build CI and update node version

src/class/workflowCheck.ts, src/index.ts
automaton encountered an error where the pull_request[0].number wasn't accessible within the workflow_run. pull_request would return an empty array when pull requests are made from forked repositories (outside main repository).
=> fix: inaccessible pull_request number in workflow_run

src/class/push.ts
cast (this.context.payload.head_commit?.id as string) to string, to resolves ts(2322) type error
=> fix: cast 'head_sha' as string

README.md
Renewed the README documentation to provide comprehensive information about the GitHub-AutoResponse application. Updated the content to offer clear insights into the features, configuration steps, usage guidelines, contributing procedures, and licensing information.
=> docs(README): Adjust README documentation

.github/ISSUE_TEMPLATE/Issues.yml, .github/PULL_REQUEST_TEMPLATE.md, SECURITY.md
This commit introduces essential elements to comply with Community Standards on GitHub. It establishes a robust security policy via `SECURITY.md`, implements a `PULL_REQUEST_TEMPLATE.md` to streamline contributions, and introduces an ISSUE_TEMPLATE via `Issues.yml` for standardized issue reporting.
=> chore: Add Security Policy, Templates, and Issue Standardization

README.md
update wrong license type in readme.md file
=> docs: update license type to ISC

.eslintrc.json, src/class/prsOpen.ts, src/class/prsReview.ts, src/class/prsSynchronize.ts, src/class/workflowCheck.ts
add parentheses in arrow function to improve code readability
=> style: add parentheses in arrow functions

src/class/prsSynchronize.ts
create a comment if the pull request commit is made by the pull request author. it checks if the sender of the prs synchronize event is the same as the pull request author before creating the comment. if they are not the same (e.g., **maintainers** pushing the commit) no comment is created.
=> refactor: create comment for prs author

.eslintrc.json, src/class/issuesComment.ts, src/class/prsOpen.ts, src/class/prsReview.ts, src/class/prsStale.ts, src/class/push.ts, src/class/workflowCheck.ts, src/index.ts
using strict equality for consistent type checking
note: bypassing review as it's not crucial (appoved by 2nd acc)
=> refactor: using strict equality operator check

src/class/prsReview.ts
fix wrong payload when reviewPrs
=> fix(prsReview): adjust author_association payload

src/class/prsReview.ts
tag maintainers for non user prs
=> feat(prs): tag maintainers for non user prs

src/class/prsOpen.ts
give feedback to users by listing specific rules that need to be set to true
=> refactor: improve tsconfig validation to report missing rules

src/class/push.ts, src/index.ts, src/structures/type.ts
=> style: change naming convention
